name = "insurify-router"
main = "router.js"
compatibility_date = "2023-05-18"

# When deployed, this Worker will handle requests for all of your domains
# You can view and edit in the Cloudflare dashboard after deployment

[build]
command = ""
[build.upload]
format = "service-worker"

[triggers]
crons = [] 